params_light <- function(learning_rate=0.05,
                         min_data_in_leaf=20,
                         feature_fraction=1,
                         bagging_fraction=1,
                         bagging_freq=1,
                         lambda_l1 = 0,
                         lambda_l2 = 0,
                         min_gain_to_split = 0,
                         max_bin = 127,
                         max_depth = 20,
                         num_leaves = 63,
                         xgboost_dart_mode = F,
                         min_data_per_group = 100,
                         cat_smooth = 10,
                         cat_l2 = 10,
                         max_cat_to_onehot = 4) {
  
    model_params <- expand.grid(learning_rate=learning_rate,
                                min_data_in_leaf=min_data_in_leaf,
                                feature_fraction=feature_fraction,
                                bagging_fraction=bagging_fraction,
                                lambda_l1 = lambda_l1,
                                lambda_l2 = lambda_l2,
                                min_gain_to_split = min_gain_to_split,
                                max_bin = max_bin,
                                max_depth = max_depth,
                                num_leaves = num_leaves,
                                xgboost_dart_mode = xgboost_dart_mode,
                                min_data_per_group = min_data_per_group,
                                cat_smooth = cat_smooth,
                                cat_l2 = cat_l2,
                                max_cat_to_onehot = max_cat_to_onehot)
    return(model_params)
}
